//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NDTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NDTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDSailing.App_GlobalResources.NDTranslations", typeof(NDTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string backToList {
            get {
                return ResourceManager.GetString("backToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Member.
        /// </summary>
        public static string createMember {
            get {
                return ResourceManager.GetString("createMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Successful.
        /// </summary>
        public static string creationSuccessful {
            get {
                return ResourceManager.GetString("creationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Culture.
        /// </summary>
        public static string currentCulture {
            get {
                return ResourceManager.GetString("currentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing to database.
        /// </summary>
        public static string dbWritingError {
            get {
                return ResourceManager.GetString("dbWritingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to delete.
        /// </summary>
        public static string deleteError {
            get {
                return ResourceManager.GetString("deleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion un-successful.
        /// </summary>
        public static string deleteFail {
            get {
                return ResourceManager.GetString("deleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion successful.
        /// </summary>
        public static string deleteSuccess {
            get {
                return ResourceManager.GetString("deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string deleteSure {
            get {
                return ResourceManager.GetString("deleteSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downwind Tack Sailing Club.
        /// </summary>
        public static string downwind {
            get {
                return ResourceManager.GetString("downwind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Member.
        /// </summary>
        public static string editMember {
            get {
                return ResourceManager.GetString("editMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Successful.
        /// </summary>
        public static string editSuccess {
            get {
                return ResourceManager.GetString("editSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be similar format to: N_dahlquist@live.ca.
        /// </summary>
        public static string emailFormat {
            get {
                return ResourceManager.GetString("emailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string homePhone {
            get {
                return ResourceManager.GetString("homePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on insert.
        /// </summary>
        public static string insertException {
            get {
                return ResourceManager.GetString("insertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be numeric..
        /// </summary>
        public static string integer {
            get {
                return ResourceManager.GetString("integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be numeric.  {0} cannot be empty or just blanks..
        /// </summary>
        public static string integerEmpty {
            get {
                return ResourceManager.GetString("integerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages Index.
        /// </summary>
        public static string languageIndex {
            get {
                return ResourceManager.GetString("languageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        public static string memberId {
            get {
                return ResourceManager.GetString("memberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Listing.
        /// </summary>
        public static string memberListing {
            get {
                return ResourceManager.GetString("memberListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member with this ID already exists..
        /// </summary>
        public static string memberOnFile {
            get {
                return ResourceManager.GetString("memberOnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should match the phone number pattern 123-123-1234.
        /// </summary>
        public static string phoneError {
            get {
                return ResourceManager.GetString("phoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in the format A1A 1A1.
        /// </summary>
        public static string postalError {
            get {
                return ResourceManager.GetString("postalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty or just blanks. {0} must be 6-7 characters in length.
        /// </summary>
        public static string postalRequiredFormat {
            get {
                return ResourceManager.GetString("postalRequiredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string provinceCode {
            get {
                return ResourceManager.GetString("provinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province code is not on file.
        /// </summary>
        public static string provinceInvalid {
            get {
                return ResourceManager.GetString("provinceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province code must be 2 letters in length.
        /// </summary>
        public static string provinceLength {
            get {
                return ResourceManager.GetString("provinceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty or just blanks.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse&apos;s First Name.
        /// </summary>
        public static string spouseFirstName {
            get {
                return ResourceManager.GetString("spouseFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required if {1} is entered..
        /// </summary>
        public static string spouseFirstRequired {
            get {
                return ResourceManager.GetString("spouseFirstRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse&apos;s Last Name.
        /// </summary>
        public static string spouseLastName {
            get {
                return ResourceManager.GetString("spouseLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be from {1} to {2} characters long.
        /// </summary>
        public static string StringLengthMinMax {
            get {
                return ResourceManager.GetString("StringLengthMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Query.
        /// </summary>
        public static string submitQuery {
            get {
                return ResourceManager.GetString("submitQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Exempt.
        /// </summary>
        public static string taskExempt {
            get {
                return ResourceManager.GetString("taskExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Canada Post.
        /// </summary>
        public static string useCanadaPost {
            get {
                return ResourceManager.GetString("useCanadaPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Joined.
        /// </summary>
        public static string yearJoined {
            get {
                return ResourceManager.GetString("yearJoined", resourceCulture);
            }
        }
    }
}
