//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class annualFeeStructure
    {
        public int year { get; set; }
        public Nullable<double> annualFee { get; set; }
        public Nullable<double> earlyDiscountedFee { get; set; }
        public Nullable<System.DateTime> earlyDiscountEndDate { get; set; }
        public Nullable<System.DateTime> renewDeadlineDate { get; set; }
        public Nullable<double> taskExemptionFee { get; set; }
        public Nullable<double> secondBoatFee { get; set; }
        public Nullable<double> thirdBoatFee { get; set; }
        public Nullable<double> forthAndSubsequentBoatFee { get; set; }
        public Nullable<double> nonSailFee { get; set; }
        public Nullable<System.DateTime> newMember25DiscountDate { get; set; }
        public Nullable<System.DateTime> newMember50DiscountDate { get; set; }
        public Nullable<System.DateTime> newMember75DiscountDate { get; set; }
    }
}
