//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boatType
    {
        public boatType()
        {
            this.boats = new HashSet<boat>();
            this.parkings = new HashSet<parking>();
        }
    
        public int boatTypeId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool chargeable { get; set; }
        public bool sail { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<boat> boats { get; set; }
        public virtual ICollection<parking> parkings { get; set; }
    }
}
