//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boat
    {
        public int boatId { get; set; }
        public Nullable<int> memberId { get; set; }
        public string boatClass { get; set; }
        public string hullColour { get; set; }
        public string sailNumber { get; set; }
        public Nullable<double> hullLength { get; set; }
        public Nullable<int> boatTypeId { get; set; }
        public string parkingCode { get; set; }
    
        public virtual boatType boatType { get; set; }
        public virtual member member { get; set; }
        public virtual parking parking { get; set; }
    }
}
