//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership
    {
        public int membershipId { get; set; }
        public int memberId { get; set; }
        public int year { get; set; }
        public string membershipTypeName { get; set; }
        public float fee { get; set; }
        public string comments { get; set; }
        public bool paid { get; set; }
    
        public virtual member member { get; set; }
        public virtual membershipType membershipType { get; set; }
    }
}
