//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberTask
    {
        public int memberTaskId { get; set; }
        public Nullable<System.DateTime> wednesdayDate { get; set; }
        public Nullable<int> taskId { get; set; }
        public Nullable<int> memberId { get; set; }
        public string comment { get; set; }
    
        public virtual member member { get; set; }
        public virtual task task { get; set; }
    }
}
