//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parking
    {
        public parking()
        {
            this.boats = new HashSet<boat>();
        }
    
        public string parkingCode { get; set; }
        public Nullable<int> boatTypeId { get; set; }
        public string actualBoatId { get; set; }
    
        public virtual ICollection<boat> boats { get; set; }
        public virtual boatType boatType { get; set; }
    }
}
