//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class province
    {
        public province()
        {
            this.members = new HashSet<member>();
        }
    
        public string provinceCode { get; set; }
        public string name { get; set; }
        public string countryCode { get; set; }
    
        public virtual country country { get; set; }
        public virtual ICollection<member> members { get; set; }
    }
}
