//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSailing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sailSQLContext : DbContext
    {
        public sailSQLContext()
            : base("name=sailSQLContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<annualFeeStructure> annualFeeStructures { get; set; }
        public virtual DbSet<boat> boats { get; set; }
        public virtual DbSet<boatType> boatTypes { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<membership> memberships { get; set; }
        public virtual DbSet<membershipType> membershipTypes { get; set; }
        public virtual DbSet<memberTask> memberTasks { get; set; }
        public virtual DbSet<parking> parkings { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<surcharge> surcharges { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<task> tasks { get; set; }
    }
}
